[package]
name = "crunch_eval"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4.0"

[dev-dependencies]
criterion = "0.4.0"
evalexpr = "8.1.0"

[[bench]]
name = "bench"
harness = false
